# vim ft=yaml
#
# travis-ci.org definition for NumPy vbench tests -- it will just
# verify that all benchmarks are correctly functioning with current
# system-wide installation of numpy. NeuroDebian repository is added
# for up-to-date pandas.
#
# We pretend to be erlang because we need can't use the python support in
# travis-ci; it uses virtualenvs, they do not have numpy
# and it is impractical to build them over and over again

language: erlang
before_install:
    - git submodule init
    - git submodule update
    - sudo apt-get update -qq
    - sudo apt-get install lsb-release
    - source /etc/lsb-release
    - echo ${DISTRIB_CODENAME}
    - wget -O- http://neuro.debian.net/lists/${DISTRIB_CODENAME}.us-nh.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
    - sudo apt-key adv --recv-keys --keyserver pgp.mit.edu 2649A5A9
    - sudo apt-get update -qq
    - sudo apt-cache policy           # What is actually available?
    - sudo apt-get install python-numpy python-pandas python-sqlalchemy git
script:
    - ./run_suite.sh verify
